// <auto-generated />
using System;
using Hermes.Infrastracture.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hermes.Infrastructure.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230702040944_Added Report Requested column")]
    partial class AddedReportRequestedcolumn
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Hermes.Domain.MailRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateRequested")
                        .HasColumnType("DateTime")
                        .HasColumnName("DateRequested");

                    b.Property<string>("DoctorUsername")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("DoctorUsername");

                    b.Property<string>("PatientUsername")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("PatientUsername");

                    b.Property<string>("ReportRequested")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("ReportRequested");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Status");

                    b.HasKey("Id");

                    b.ToTable("MailRequests");
                });

            modelBuilder.Entity("Hermes.Domain.MailTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MailBody")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("MailBody");

                    b.Property<string>("MailSubject")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("MailSubject");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Name");

                    b.Property<string>("SenderEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("SenderEmail");

                    b.Property<string>("TargetEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("TargetEmail");

                    b.Property<string>("UserID")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("UserID");

                    b.HasKey("Id");

                    b.ToTable("MailTemplates");
                });
#pragma warning restore 612, 618
        }
    }
}
